# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf20fb3dddbd857c830692c067d8edd5a23fb15d35b22de9537a643267ccb9eff540416146355d3f9065116d59726b78d77944b42fce1639cb63bcedf5bd2d17

test:
  secret_key_base: b53546f2398976cf633b58f0d477a836f8111ff28bde5db061d0cf635328f801a0f036db545b0a50a89af51c4bdc74179bb14f8d61cecf9440fddd18162736af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
